### ISSUE TITLE
CWS files upload and then fail to populate Printables

### ISSUE THREAD

**Issue by WGAndrew** [area515/Photonic3D#297]
Attempting to upload a CWS file results in nothing being added to the Printables tab in Photonic. 
`2016-11-28 15:15:29,724 ERROR o.a.r.j.CreationWorkshopSceneFileProcessor [qtp32195482-14] Unable to open uploaded zip file
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:273) ~[?:1.8.0_65]
	at org.area515.resinprinter.job.CreationWorkshopSceneFileProcessor.zipHasGCode(CreationWorkshopSceneFileProcessor.java:314) [photonic3d.jar:?]
	at org.area515.resinprinter.job.CreationWorkshopSceneFileProcessor.acceptsFile(CreationWorkshopSceneFileProcessor.java:49) [photonic3d.jar:?]
`

Present in v1.0.14

Testing files and log file attached

**Comment by WGAndrew** [comment]
[photonic bug.zip](https://github.com/area515/Photonic3D/files/616732/photonic.bug.zip)

**Comment by WesGilster** [comment]
This is a bad file(no attached gcode). No print file processor is willing to take responsibility for attempting to print it. Here is the response the browser is getting from the PrintableService when you attempt to upload. I fixed the content type of the return type since it isn't being sent properly, but the response is being ignored anyway.

![image](https://cloud.githubusercontent.com/assets/2424628/20692513/25d66094-b59e-11e6-8ec7-5e64445f1354.png)

**Comment by WesGilster** [comment]
Latest version shows error messages coming back from uploads

**Comment by WesGilster** [comment]
Here's an example:
![image](https://cloud.githubusercontent.com/assets/2424628/20696647/f348931a-b5b9-11e6-8e3f-0f73f093cd2b.png)
